use std::fs;
use std::io::Write;
use std::process;

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 {
        print_usage();
        process::exit(1);
    }

    match args[1].as_str() {
        "render" => cmd_render(&args[2..]),
        "check" => cmd_check(&args[2..]),
        "params" => cmd_params(&args[2..]),
        "help" | "--help" | "-h" => print_usage(),
        other => {
            eprintln!("unknown command: {}", other);
            print_usage();
            process::exit(1);
        }
    }
}

fn print_usage() {
    eprintln!("synth - DSL-powered synthesizer

USAGE:
    synth render <song.synth> [-o output.wav] [--bars N]
    synth check <song.synth>
    synth params [bass|fm|keys|beats] [--json]

COMMANDS:
    render    Parse, compile, and render a .synth file to WAV
    check     Parse and validate a .synth file (no audio output)
    params    Print the module parameter reference (markdown, or JSON with --json)
    help      Show this help
");
}

fn cmd_params(args: &[String]) {
    use synth_core::params::{self, ModuleKind, Range};

    let json = args.iter().any(|a| a == "--json");
    let kinds: Vec<ModuleKind> = match args.iter().find(|a| !a.starts_with("--")) {
        Some(name) => match ModuleKind::from_str(name) {
            Some(k) => vec![k],
            None => {
                eprintln!("error: unknown module '{}' (expected bass, fm, keys, or beats)", name);
                std::process::exit(2);
            }
        },
        None => ModuleKind::ALL.to_vec(),
    };

    if json {
        println!("{{");
        for (ki, kind) in kinds.iter().enumerate() {
            println!("  \"{}\": [", kind.as_str());
            let specs = params::specs(*kind);
            for (i, s) in specs.iter().enumerate() {
                let (ty, extra) = match s.range {
                    Range::Unit => ("unit", String::new()),
                    Range::Bipolar => ("bipolar", String::new()),
                    Range::Gain { max } => ("gain", format!(", \"max\": {}", max)),
                    Range::Choice(names) => {
                        let list: Vec<String> = names.iter().map(|n| format!("\"{}\"", n)).collect();
                        ("choice", format!(", \"choices\": [{}]", list.join(", ")))
                    }
                };
                println!(
                    "    {{\"name\": \"{}\", \"type\": \"{}\", \"min\": {}, \"max\": {}{}, \"default\": {}, \"doc\": \"{}\"}}{}",
                    s.name, ty, s.range.min(), s.range.max(), extra, s.default,
                    s.doc.replace('"', "\\\""),
                    if i + 1 < specs.len() { "," } else { "" }
                );
            }
            println!("  ]{}", if ki + 1 < kinds.len() { "," } else { "" });
        }
        println!("}}");
        return;
    }

    println!("# Module parameters\n");
    println!("Values are floats in the listed range. `choice` params take an option name");
    println!("(`waveform half_sine`); a numeric value encodes as index / (options - 1).");
    println!("FM modules also accept `op<N>_envelope <attack> <decay> <sustain> <release>` as a");
    println!("shorthand for the four per-operator envelope params.");
    println!("Generated by `synth params`; do not edit by hand.\n");
    for kind in kinds {
        println!("## {}\n", kind.as_str());
        println!("| name | range | default | description |");
        println!("|------|-------|---------|-------------|");
        for s in params::specs(kind) {
            let (range, default) = match s.range {
                Range::Choice(names) => (
                    format!("choice: {}", names.join(", ")),
                    format!("`{}`", s.choice_name(s.default).unwrap_or("")),
                ),
                _ => (s.range.describe(), format!("{}", s.default)),
            };
            println!("| `{}` | {} | {} | {} |", s.name, range, default, s.doc);
        }
        println!();
    }
}

fn cmd_check(args: &[String]) {
    if args.is_empty() {
        eprintln!("error: missing input file");
        eprintln!("usage: synth check <song.synth>");
        process::exit(1);
    }

    let path = &args[0];
    let source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read '{}': {}", path, e);
            process::exit(1);
        }
    };

    // Parse
    let ast = match synth_core::dsl::parse(&source) {
        Ok(ast) => {
            eprintln!("  parse OK");
            ast
        }
        Err(errs) => {
            eprintln!("parse errors:");
            for e in &errs {
                eprintln!("  line {}: {}", e.line, e.message);
            }
            process::exit(1);
        }
    };

    // Compile
    match synth_core::dsl::compiler::compile(&ast) {
        Ok(compiled) => {
            eprintln!("  compile OK");
            eprintln!("  {} instruments, {} patterns, {} tracks, {} buses",
                compiled.instruments.len(),
                compiled.patterns.len(),
                compiled.tracks.len(),
                compiled.buses.len(),
            );
            if !compiled.scenes.is_empty() {
                eprintln!("  {} scenes, arrangement: {} entries",
                    compiled.scenes.len(),
                    compiled.arrangement.len(),
                );
            }
            eprintln!("  tempo: {} BPM", compiled.globals.tempo);
        }
        Err(errs) => {
            eprintln!("compile errors:");
            for e in &errs {
                eprintln!("  {}", e);
            }
            process::exit(1);
        }
    }

    eprintln!("{}: OK", path);
}

fn cmd_render(args: &[String]) {
    if args.is_empty() {
        eprintln!("error: missing input file");
        eprintln!("usage: synth render <song.synth> [-o output.wav] [--bars N]");
        process::exit(1);
    }

    let path = &args[0];
    let mut output_path = String::from("output.wav");
    let mut bars: Option<u32> = None;

    // Parse flags
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "-o" | "--output" => {
                i += 1;
                if i < args.len() {
                    output_path = args[i].clone();
                }
            }
            "--bars" => {
                i += 1;
                if i < args.len() {
                    bars = args[i].parse().ok();
                }
            }
            _ => {}
        }
        i += 1;
    }

    let source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read '{}': {}", path, e);
            process::exit(1);
        }
    };

    eprintln!("loading {}...", path);

    let mut engine = match synth_core::song_engine::SongEngine::from_source(&source) {
        Ok(e) => e,
        Err(msg) => {
            eprintln!("{}", msg);
            process::exit(1);
        }
    };

    let render_bars = bars.unwrap_or_else(|| {
        let arr = engine.arrangement_bars();
        if arr > 0 { arr } else { 4 }
    });

    eprintln!("rendering {} bars at {} BPM...", render_bars, engine.tempo());

    let (out_l, out_r) = engine.render(render_bars);

    eprintln!("writing {} ({} samples, {:.1}s)...",
        output_path,
        out_l.len(),
        out_l.len() as f32 / 44100.0,
    );

    write_wav_stereo(&output_path, &out_l, &out_r, 44100);
    eprintln!("done.");
}

fn write_wav_stereo(path: &str, samples_l: &[f32], samples_r: &[f32], sample_rate: u32) {
    let num_frames = samples_l.len().min(samples_r.len()) as u32;
    let bits_per_sample: u16 = 16;
    let num_channels: u16 = 2;
    let byte_rate = sample_rate * (bits_per_sample as u32 / 8) * num_channels as u32;
    let block_align = num_channels * (bits_per_sample / 8);
    let data_size = num_frames * (bits_per_sample as u32 / 8) * num_channels as u32;
    let file_size = 36 + data_size;

    let mut file = fs::File::create(path).expect("Failed to create WAV file");

    file.write_all(b"RIFF").unwrap();
    file.write_all(&file_size.to_le_bytes()).unwrap();
    file.write_all(b"WAVE").unwrap();
    file.write_all(b"fmt ").unwrap();
    file.write_all(&16u32.to_le_bytes()).unwrap();
    file.write_all(&1u16.to_le_bytes()).unwrap();
    file.write_all(&num_channels.to_le_bytes()).unwrap();
    file.write_all(&sample_rate.to_le_bytes()).unwrap();
    file.write_all(&byte_rate.to_le_bytes()).unwrap();
    file.write_all(&block_align.to_le_bytes()).unwrap();
    file.write_all(&bits_per_sample.to_le_bytes()).unwrap();
    file.write_all(b"data").unwrap();
    file.write_all(&data_size.to_le_bytes()).unwrap();

    let clamp = |s: f32| -> i16 {
        let c = s.clamp(-1.0, 1.0);
        (c * 32767.0) as i16
    };

    for i in 0..num_frames as usize {
        file.write_all(&clamp(samples_l[i]).to_le_bytes()).unwrap();
        file.write_all(&clamp(samples_r[i]).to_le_bytes()).unwrap();
    }
}
